### ISSUE TITLE
The word 'trueblocks' shows up twice under topics in the blog.

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#101] opened 2022-01-03 22:24 UTC

**Comment by MattDodsonEnglish** [comment] 2022-01-04 17:43
This is actually a duplicate of https://github.com/TrueBlocks/trueblocks-docs/issues/81

Unfortunately, this applies not just to TrueBlocks tags, but to any tag. And, I don't know how to fix it. I've tagged that issue `hugo help needed` if we get any hugo-knowledgable volunteers who come along.

I'm also learning more about hugo, so maybe I'll be able to fix it myself one day.

**Closed** 2022-01-04 18:30 UTC
