### ISSUE TITLE
In docs/prologue, add core set of values

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-docs#85] opened 2021-10-04 13:59 UTC
@tjayrush 

In the directory, `content/docs/prologue`, I have made a _draft_ version a new article "Design philosophy".
https://github.com/TrueBlocks/trueblocks-docs/blob/master/content/docs/prologue/design-philosophy.md

## Adding technical design values

If you run `hugo server --buildDrafts` , the page currently looks like this
![Bare design philosophy](https://user-images.githubusercontent.com/47385188/135862913-fbf95c32-7b42-4d1e-b9a4-10d25e4311ea.png)

While I think the mantras are a great start for the more philosophical side, I'd also like the article to have some explicit statement of _core technical values_.

The inspiration for this idea came from [this great talk by Brian Cantrill](https://youtu.be/2wZ1pCpJUIM?t=257). In that link, I have timestamped the discussion about design values. That part is only 6 or 7 minutes long, worth a watch.

In that talk, he creates this list of design values. This is not a canonical list---he acknowledges that it's arbitrary and haphazard--- but I think it's a good starting point. Basically, we all agree that these characteristics are important, but no application can do all characteristics well. 

When a programmer makes a decision to emphasize one characteristic over another, then the programmer has decided on a core value. For example, C emphasizes portability, interoperability, simplicity, and performance. 
 
![haphazard list of design values](https://user-images.githubusercontent.com/47385188/135863774-a9b216f8-3aef-4ed3-bba5-983b445f3135.png)

 ## Why do this?
 
 For a few reasons:
 * Communicates to readers key design decisions
 * Clarifies design decisions to designer.
 * Will save you explanation time in the future, if a prospective user or builder asks "Why do you refuse to implement this?"

**Comment by MattDodsonEnglish** [comment] 2021-10-04 15:37
Oh the spreadsheet is perfect! I think I could adapt something very close to exactly this for the "design philosophy" document.

When I do, I'll make a pull request, just to double check before it's live.

Two questions:
* the numbers represent "weight," right? With smallest number what never gets traded off?
* About compatibility and portability, you wrote:

 > Depends on programming language, so not a concern
 
 Do you mind briefly explaining what this means? I'm just not familiar these concepts.

**Comment by tjayrush** [comment] 2021-10-04 15:43
Yes. The numbers are just how I sorted the list. You can ignore them.

About portability
	Our code is Typescript, C++ and Go, so if they are portable, so are we. The data we produce is binary, but we share it via IPFS, so it’s 100% portable. Therefore, all portability stuff is kind of out of our hands.

Same goes for compatibility — it depends more on the coding languages than anything we do…if the language works on an operating system, we will work on an operating system — excluding MS Windows which I do not consider to be an operating system...

**Comment by MattDodsonEnglish** [comment] 2021-10-04 17:52
A few more questions, before I commit this to our site.

For *Transparency,* does that include having open source code? It seems like that's also essential to reproducibility, which is essential to decentralization, which is the key value.

Actually, as soon as I typed it, I realized that have these discussions in a public-facing forum (the gh issue) is another form of transparency.
---
For *Stability*, is that per-version? Because it seems like TrueBlocks is happy to accept some breaking changes, if they improve usability, maintainability, or fix something. Also some changes have to be made for Ethereum upstream.

Or, is fixing something what is meant by "integrity"? In that case, I suppose breaking fixes for better data quality is inline with how you ranked it.
---
On that note, can you explain what you mean by *integrity*, *rigor*, and *'golden' nature?

How does being "consented to" imply being hashed? 



> 
<google-sheets-html-origin><style type="text/css">
value| number | description|
-- | -- | --
Integrity | 25 | Related to Rigor -- preserves the 'golden' nature of consented to (i.e. hashed) data
Rigor | 25 | Related to Integrity -- preserves the 'golden' nature of consented to (i.e. hashed) data
</style>

**Comment by tjayrush** [comment] 2021-10-04 19:46
_Transparency_ in this context means _transparency_ of the data that is being constantly added to the chain. One of my biggest concerns, and a driving influence behind what I'm building, is to try to preserve that transparency. Blockchains create 'open-source data.' This means that 'everyone can see everything.' (Ignore privacy for a moment. Privacy is something that must be (and eventually will be) handled prior to putting anything on-chain.) If, as I expect, small groups of people run nodes, then small groups of people will naturally form a gatekeeping faction around the data. This is why IPFS is so important to our work. By publishing -- from my own local machine -- to IPFS, and by publishing -- from my own local machine the hash of the index to the Unchained Index smart contract -- I've purposefully circumvented anyone's ability to ever become a gatekeeper to the already transparent, but in-danger-of-becoming-captured data.

For _Stability_, TrueBlocks is happy to accept breaking changes while we're pre-version 1.0. That's a conscious choice since developing in the face of users who expect no changes will kill forward progress, and there's a ton of future work before we're settled. Once we're at version 1.0, there won't be breaking changes. So _Stability_ is important, just not yet.

_Integrity_ (to me) refers to the fact that the data being laid down on the chain is what I call "Pristine". I call it "the best data ever created by mankind" because (a) it's agreed to by 10,000 miners, and (b) it has a hash on it. Once the data is consented to and hashed, no-one can fake it -- unless _Transparency_ is violated. If the data is **not** transparent (in other words, people have to go to a data provider to ask for access to the data), then the provider themselves can ruin it's _Integrity_. This is why the word "True" is in the name of the project. It is also why we want to insert, in the actual data we produce (the chunks) the code that is used to build the data. If I can publish without fear of being captured and the data I publish carries with it instructions for re-creating that data directly from block data ("the world's best data"), then the data I'm publishing can also be considered "golden." I (nor anyone else) can have lied about the data thereby preserving its _Transparency_.

Answering the last question in a new comment...

**Comment by tjayrush** [comment] 2021-10-04 19:57
The blockchain comes to agreement on a block -- an ordering of a collection of transactions every 14 seconds. In other words, it comes to consensus. Once it does that it, it inserts the hash from the previous block into the data and hashes the bytes that make up the block and its parent's pointer. This results in a block hash. That block hash is a perfect representation of everything in the block. It can't be faked. In this sense, it's "the best data ever produced by mankind".

If I later receive that data from someone (it can be anyone), I am free to re-calculate every transaction (and every block) that led up to that block. In this way, I can be 100% certain that whatever the provider is telling me is the current block is indeed valid. This is all in the nature of blockchains.

If someone later 'derived' data from the "pristine" ("golden") data but does not provide a way to 're-produce' the 'derivation', then it's as if the "golden" data never existed. This is exactly what happens when people go to EtherScan to query the blockchain. In fact, I've not seen a single method, other than running your own node ala Erigon and dAppNode where one can be certain that the queried data is 'valid' or 'golden' or 'as good as the original blockchain data.'

So, when I say _integrity_ or _rigor_ or _golden_, I'm referring to my belief that _Transparency_ is only truly achieved if the "consented to" (i.e. "hashed") block data **and everything derived from the consented-to hashed block data** is reproducable with perfection.

I think blockchains die in their crib if only people who are running node can produce 'derived' data from the blockchain because only they have the wherewithal to do so.

I include absolutely an 'index of all appearances of every address' in the category of 'derived' and this is why I publish the same to IPFS. I derive it with perfect reproducibility and I publish it so I can never capture it once its released into the world. None of those things exist in regular web 2.0 APIs.

**Comment by MattDodsonEnglish** [comment] 2021-10-08 20:28
@tjayrush 

With this commit, I've incorporated that useful list into a full document. Currently it's still in draft status, located at in this repo at `content/docs/prologue/design-philosophy.md'

Do you mind giving it a review? Feel free to add modify anything---just commit on top of it. When it's down, we can publishing it live on-site: in the front matter, just switch `draft: true` to `draft: false`.

(To preview the local site with drafts, run `hugo server --buildDrafts`)

**Closed** 2021-10-11 00:29 UTC
